"""add cases and golden_images, add engineer role

Revision ID: 288f8bcaed40
Revises: 748124a3cba1
Create Date: 2026-09-18 09:22:36.620379

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "288f8bcaed40"
down_revision: str | Sequence[str] | None = "748124a3cba1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "golden_images",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("board_id", sa.String(), nullable=False),
        sa.Column("component_ref", sa.String(), nullable=False),
        sa.Column("package", sa.String(), nullable=False),
        sa.Column("feature", sa.String(), nullable=False),
        sa.Column("stored_filename", sa.String(), nullable=False),
        sa.Column("registered_by_user_id", sa.String(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["registered_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "board_id", "component_ref", "package", "feature", name="uq_golden_images_lookup_key"
        ),
    )
    op.create_index(op.f("ix_golden_images_board_id"), "golden_images", ["board_id"], unique=False)
    op.create_index(
        op.f("ix_golden_images_component_ref"), "golden_images", ["component_ref"], unique=False
    )
    op.create_table(
        "cases",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("created_by_user_id", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("board_id", sa.String(), nullable=False),
        sa.Column("component_ref", sa.String(), nullable=False),
        sa.Column("package", sa.String(), nullable=True),
        sa.Column("feature", sa.String(), nullable=True),
        sa.Column("issue_symptom", sa.String(), nullable=True),
        sa.Column("image_id", sa.String(), nullable=False),
        sa.Column("inspection_xml_id", sa.String(), nullable=True),
        sa.Column("golden_image_id", sa.String(), nullable=True),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("region_confidence", sa.Float(), nullable=True),
        sa.Column("defect_model", sa.String(), nullable=True),
        sa.Column("defect_label", sa.String(), nullable=True),
        sa.Column("defect_confidence", sa.Float(), nullable=True),
        sa.Column("defect_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("measurement_validation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("explainability_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("observations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("resolved_by_user_id", sa.String(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_note", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["golden_image_id"],
            ["golden_images.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cases_created_by_user_id"), "cases", ["created_by_user_id"], unique=False
    )
    op.create_index(op.f("ix_cases_sequence_number"), "cases", ["sequence_number"], unique=True)
    op.create_index(op.f("ix_cases_status"), "cases", ["status"], unique=False)
    op.create_index("ix_cases_status_created_at", "cases", ["status", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_cases_status_created_at", table_name="cases")
    op.drop_index(op.f("ix_cases_status"), table_name="cases")
    op.drop_index(op.f("ix_cases_sequence_number"), table_name="cases")
    op.drop_index(op.f("ix_cases_created_by_user_id"), table_name="cases")
    op.drop_table("cases")
    op.drop_index(op.f("ix_golden_images_component_ref"), table_name="golden_images")
    op.drop_index(op.f("ix_golden_images_board_id"), table_name="golden_images")
    op.drop_table("golden_images")
    # ### end Alembic commands ###
